### ISSUE TITLE
Bug: Possible database error, can't add items to shopping list

### ISSUE THREAD

**Issue by Snamhdaen** [TomBursch/kitchenowl#193]
### Is this urgent?

Yes

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

latest

### What's the problem 🤔

I have run into another what I presume to be database error. I can't manage my grocery lists anymore. Logs look like this:
`front_1  | 192.168.178.31 - - [03/Jul/2023:20:24:14 +0000] "POST /api/shoppinglist/1/add-item-by-name HTTP/1.1" 500 20 "http://frege.lan:7002/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0" "-"
back_1   | [pid: 18|app: 0|req: 102/102] 192.168.178.31 () {50 vars in 1112 bytes} [Mon Jul  3 20:24:14 2023] POST /api/shoppinglist/1/add-item-by-name => generated 20 bytes in 19 msecs (HTTP/1.1 500) 2 headers in 98 bytes (1 switches on core 0)
back_1   | [pid: 18|app: 0|req: 103/103] 192.168.178.31 () {44 vars in 963 bytes} [Mon Jul  3 20:24:14 2023] GET /api/household/1/shoppinglist => generated 677 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
front_1  | 192.168.178.31 - - [03/Jul/2023:20:24:14 +0000] "GET /api/household/1/shoppinglist HTTP/1.1" 200 677 "http://frege.lan:7002/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0" "-"
back_1   | [2023-07-03 20:24:14,115] ERROR in config: (sqlite3.OperationalError) no such column: shoppinglist_items.created_by
back_1   | [SQL: SELECT shoppinglist_items.shoppinglist_id AS shoppinglist_items_shoppinglist_id, shoppinglist_items.item_id AS shoppinglist_items_item_id, shoppinglist_items.description AS shoppinglist_items_description, shoppinglist_items.created_by AS shoppinglist_items_created_by, shoppinglist_items.created_at AS shoppinglist_items_created_at, shoppinglist_items.updated_at AS shoppinglist_items_updated_at
back_1   | FROM shoppinglist_items JOIN item ON item.id = shoppinglist_items.item_id
back_1   | WHERE shoppinglist_items.shoppinglist_id = ? ORDER BY item.name, item.name]
back_1   | [parameters: (1,)]
back_1   | (Background on this error at: https://sqlalche.me/e/20/e3q8)`

Why is there no column created_by in my database table? Is my database out of date?

I tried running `sudo docker exec -it kitchenowl_back_1 flask db upgrade` but this gave 

`/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6c669d9ec3bd -> c058421705ec, empty message
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: file.filename

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/cli.py", line 150, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/venv/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/opt/venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/kitchenowl/migrations/env.py", line 110, in <module>
    run_migrations_online()
  File "/usr/src/kitchenowl/migrations/env.py", line 104, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/usr/src/kitchenowl/migrations/versions/c058421705ec_.py", line 75, in upgrade
    raise e
  File "/usr/src/kitchenowl/migrations/versions/c058421705ec_.py", line 69, in upgrade
    session.bulk_save_objects(files)
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4396, in bulk_save_objects
    self._bulk_save_mappings(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4566, in _bulk_save_mappings
    with util.safe_reraise():
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4555, in _bulk_save_mappings
    bulk_persistence._bulk_insert(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 199, in _bulk_insert
    result = persistence._emit_insert_statements(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: file.filename
[SQL: INSERT INTO file (filename, created_at, updated_at) VALUES (?, ?, ?)]
[parameters: ('208041b4-3ffc-4f03-a251-79ed47541975.jpg', '2023-07-03 20:27:36.936802', '2023-07-03 20:27:36.936809')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) 

What can I do? I'm running docker-compose with the recommended yaml file, still I'm running into these problems. I have a watchtower running, updating my docker containers. Might this be related to the problem?

Thanks in advance!

**Comment by TomBursch** [comment]
Thanks for already including the `flask db upgrade` log. The fix should be live in 25 min.

**Comment by Snamhdaen** [comment]
Sorry to bother you again. I tried the kitchenowl:latest and kitchenowl:dev branch with my docker-compose but the error persists. What to do?

**Comment by TomBursch** [comment]
Don't worry, you're not bothering :) 
Could you share the logs of flask db upgrade again? Or did they not change?
Will try to reproduce this again.

**Comment by Snamhdaen** [comment]
Voilà:
`WARNING: Error loading config file: /root/.docker/config.json: read /root/.docker/config.json: is a directory
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6c669d9ec3bd -> c058421705ec, empty message
Traceback (most recent call last):
  File "/opt/venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/cli.py", line 150, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/venv/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/opt/venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/kitchenowl/migrations/env.py", line 110, in <module>
    run_migrations_online()
  File "/usr/src/kitchenowl/migrations/env.py", line 104, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/usr/src/kitchenowl/migrations/versions/c058421705ec_.py", line 75, in upgrade
    raise e
  File "/usr/src/kitchenowl/migrations/versions/c058421705ec_.py", line 67, in upgrade
    files = [File(filename=f) for f in filesInUploadFolder if not File.query.filter(File.filename == f).first()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/kitchenowl/migrations/versions/c058421705ec_.py", line 67, in <listcomp>
    files = [File(filename=f) for f in filesInUploadFolder if not File.query.filter(File.filename == f).first()]
                                                                  ^^^^^^^^^^
AttributeError: type object 'File' has no attribute 'query'`

**Comment by TomBursch** [comment]
Sorry that it took so long, should be fixed now (this time for real 😄)
