### ISSUE TITLE
Bug: Issue with SSO using authentik

### ISSUE THREAD

**Issue by filipfigzalski** [TomBursch/kitchenowl#391]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

v93

### What is the client version

v0.4.21

### What platform are you using

Web, Linux

### What's the problem 🤔

I was trying to set up SSO with Authentik, but for some reason I get following issue.

### Share your logs

```Shell
back-1   | [2024-02-03 12:54:55,166] ERROR in config: {"error": "service_error", "error_description": "Remote key update from https://auth.domain.tld/application/o/kitchenowl/jwks/ failed, malformed JWKS."}
back-1   | Traceback (most recent call last):
back-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
back-1   |     rv = self.dispatch_request()
back-1   |          ^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
back-1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
back-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
back-1   |     return current_app.ensure_sync(fn)(*args, **kwargs)
back-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/usr/src/kitchenowl/app/helpers/validate_args.py", line 26, in func_wrapper
back-1   |     return func(arguments, *args, **kwargs)
back-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/usr/src/kitchenowl/app/controller/auth/auth_controller.py", line 267, in loginWithOIDC
back-1   |     tokenResponse = client.do_access_token_request(
back-1   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oic/__init__.py", line 704, in do_access_token_request
back-1   |     atr = super().do_access_token_request(
back-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/__init__.py", line 928, in do_access_token_request
back-1   |     return self.request_and_return(
back-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/__init__.py", line 823, in request_and_return
back-1   |     return self.parse_request_response(resp, response, body_type, state, **kwargs)
back-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/__init__.py", line 764, in parse_request_response
back-1   |     return self.parse_response(
back-1   |            ^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/__init__.py", line 678, in parse_response
back-1   |     verf = resp.verify(**kwargs)
back-1   |            ^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oic/message.py", line 360, in verify
back-1   |     self["id_token"] = verify_id_token(self, **kwargs)
back-1   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oic/message.py", line 310, in verify_id_token
back-1   |     idt = IdToken().from_jwt(_jws, **args)
back-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/message.py", line 665, in from_jwt
back-1   |     key = self.get_verify_keys(
back-1   |           ^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/message.py", line 590, in get_verify_keys
back-1   |     self._add_key(keyjar, jso[ent], key, _key_type, _kid, nki)
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/oauth2/message.py", line 491, in _add_key
back-1   |     "Key set summary for {}: {}".format(issuer, key_summary(keyjar, issuer))
back-1   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 1209, in key_summary
back-1   |     for key in kb.keys():
back-1   |                ^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 308, in keys
back-1   |     self._uptodate()
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 265, in _uptodate
back-1   |     if self.update():
back-1   |        ^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 289, in update
back-1   |     res = self.do_remote()
back-1   |           ^^^^^^^^^^^^^^^^
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 214, in do_remote
back-1   |     raise_exception(UpdateFailed, MALFORMED.format(self.source))
back-1   |   File "/opt/venv/lib/python3.11/site-packages/oic/utils/keyio.py", line 43, in raise_exception
back-1   |     raise excep(_err, "application/json")


front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:49 +0000] "GET /version.json?cachebuster=1706964889567 HTTP/1.1" 200 92 "https://recipe.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:49 +0000] "GET /flutter_service_worker.js?v=3875269676 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:49 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V HTTP/1.1" 200 79 "https://recipe.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:49 +0000] "GET /api/onboarding HTTP/1.1" 200 21 "https://recipe.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:52 +0000] "GET /api/auth/oidc?provider=custom HTTP/1.1" 200 327 "https://recipe.domain.tld/signin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:53 +0000] "GET /signin/redirect?code=9db87a15e21f449f87ce5c05bfffb8a4&state=9QtEzNFuCrRWsV5d HTTP/1.1" 200 3413 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:53 +0000] "GET /flutter_service_worker.js?v=3875269676 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:54 +0000] "GET /flutter_service_worker.js?v=3875269676 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:54 +0000] "GET /version.json?cachebuster=1706964894342 HTTP/1.1" 200 92 "https://recipe.domain.tld/signin/redirect?code=9db87a15e21f449f87ce5c05bfffb8a4&state=9QtEzNFuCrRWsV5d" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:54 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V HTTP/1.1" 200 79 "https://recipe.domain.tld/signin/redirect?code=9db87a15e21f449f87ce5c05bfffb8a4&state=9QtEzNFuCrRWsV5d" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:54 +0000] "GET /api/onboarding HTTP/1.1" 200 21 "https://recipe.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:55 +0000] "POST /api/auth/callback HTTP/1.1" 500 20 "https://recipe.domain.tld/signin/redirect?code=9db87a15e21f449f87ce5c05bfffb8a4&state=9QtEzNFuCrRWsV5d" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
front-1  | 10.1.1.1 - - [03/Feb/2024:12:54:55 +0000] "GET /api/onboarding HTTP/1.1" 200 21 "https://recipe.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" "-"
```

### Share your configuration

```yml
--- docker-compose.yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - 8012:80
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:


--- .env
JWT_SECRET_KEY=KId1wkjVYzhu87VhExPiz0YJk0GVhWQuHZUk2CAyv2whxDTAlmPuatYV8OHAIMDW

FRONT_URL=https://recipe.domain.tld

OIDC_ISSUER=https://auth.domain.tld/application/o/kitchenowl/
OIDC_CLIENT_ID=[redacted]
OIDC_CLIENT_SECRET=[redacted]
```

**Comment by shangri26199** [comment]
After seeeing this i decided to test this out myself.
Using the same configuration as you is working for me.
Authentik [2024.2.1] , used the new application wizard
Kitchenowl Server v93
Kitchenowl Client v0.4.21 (firefox web, windows10)

I can't get it to work for my android device and currently debugging it.

**Comment by TomBursch** [comment]
Could this be related to #428?

**Comment by shangri26199** [comment]
Sorry i forgot to report back. Auth against authentik sso works perfectly fine.
My .env file:

FRONT_URL=https://kitchenowl.example.tld
OIDC_ISSUER=https://authentik.example.tld/application/o/kitchenowl/
OIDC_CLIENT_ID=XX
OIDC_CLIENT_SECRET=XXX

In authentik using the application wizard and afterwords chaning the redirect URLs to the following
kitchenowl:///signin/redirect https://kitchenowl.exmaple.tld/signin/redirect

works for everyone using my service, including android,ios and me on win10 desktop+firefox

**Comment by J000K3R** [comment]
> Sorry i forgot to report back. Auth against authentik sso works perfectly fine. My .env file:
> 
> FRONT_URL=https://kitchenowl.example.tld OIDC_ISSUER=https://authentik.example.tld/application/o/kitchenowl/ OIDC_CLIENT_ID=XX OIDC_CLIENT_SECRET=XXX
> 
> In authentik using the application wizard and afterwords chaning the redirect URLs to the following kitchenowl:///signin/redirect https://kitchenowl.exmaple.tld/signin/redirect
> 
> works for everyone using my service, including android,ios and me on win10 desktop+firefox

can you please describe in a little more detail where the two redirect URLs have to be entered in Authentik?

The Authentik login works for me, but then it return to the normal Kitchenowl login page.
And how can I set it up that I get to the Authentik login right away?

**Comment by reddwarf666** [comment]
I seem to face the same issue as @J000K3R 

Navigate to https://kitchenowl.domain.com, I get redirected to the Authentik login page, I login and use a passkey, Authentik says I'm logged in.
KitchenOwl shows it's login page with username and password and a button "Sign in with OIDC". A bit odd as I just did that but ok, I press that button, Authentik precesses for a bit and tells me I'm loggid in. Get back to the KitchenOwl login page.
When I try to use my username and password, KitchenOwl tells me the username or password is wrong. I'm quite sure I gave the correct credentials.
As it is now I cannot get into KitchenOwl at all.

I started KitchenOwl without any user and when I first navigated to the KitchenOwl URL I wqs greeted to create the first user. Got an email to confirm my account. I looked at the SqlLite DB and I see my account and it is indeed verified.

FYI: I use [Godoxy](https://github.com/yusing/godoxy) as reverse proxy

My compose file:
```
services:
  kitchenowl-front:
    image: tombursch/kitchenowl-web:latest
    container_name: kitchenowl-front
    restart: unless-stopped
    env_file:
      - .env
    environment:
     BACK_URL: kitchenowl-back:5000
    labels:
      proxy.aliases: kitchenowl
      proxy.kitchenowl.scheme: http
      proxy.kitchenowl.middlewares.redirectHTTP:
    volumes:
      - ./data:/data
    depends_on:
      - kitchenowl-back

  kitchenowl-back:
    image: tombursch/kitchenowl-backend:latest
    container_name: kitchenowl-back
    restart: unless-stopped
    env_file:
      - .env
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONT_URL: ${FRONT_URL}
    volumes:
      - ./data:/data
```

My .env file:
```

# General Environment Settings
TZ=Europe/Amsterdam
UID=1000
GID=1000

# JWT Settings
JWT_SECRET_KEY=[redacted]
JWT_REFRESH_TOKEN_EXPIRES=180

# Server settings
FRONT_URL=https://kitchenowl.domain.com
DISABLE_USERNAME_PASSWORD_LOGIN=true
DISABLE_ONBOARDING=false
OPEN_REGISTRATION=false
EMAIL_MANDATORY=false
SKIP_UPGRADE_DEFAULT_ITEMS=false
STORAGE_PATH=/data
DB_DRIVER=sqlite
DB_NAME=${STORAGE_PATH}/database.db

# E-Mail Settings
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USE_TLS=true
SMTP_USER=[redacted]@gmail.com
SMTP_PASS=[redacted]
SMTP_FROM=[redacted]@gmail.com
SMTP_REPLY_TO=[redacted]@gmail.com

# OIDC Settings
OIDC_ISSUER=https://auth.domain.com/application/o/kitchenowl/
OIDC_CLIENT_ID=[redacted]
OIDC_CLIENT_SECRET=[redacted]
```

Authentik provider settings for KitcheOwl:
```
Redirect URIs/Origins:
https://kitchenowl.domain.com/signin/redirect
kitchenowl:///signin/redirect

Scopes:
email, profile, openid, offline_access
```

Would appreciate some help with this as I'm stuck and have basically no access to KitchenOwl anymore.

**Comment by TomBursch** [comment]
@reddwarf666 I'm not sure I can help you with the SSO issue. But you've disabled password based logins in your config. Enable it and you should at least be able to use it again. 

```
DISABLE_USERNAME_PASSWORD_LOGIN=false
```

**Comment by reddwarf666** [comment]
@TomBursch Right, this is indeed why username/password did not work. Thanks!

And I solved the OIDC/SSO issue I faced. It seems that my account in KitchenOwl was not linked to OIDC. I remembered reading something about linking with OIDC when I went through the docs and went to have a look at my account, it was indeed unlinked. I linked it and now it works!

The reason I kinda forgot about this was because I made the assumption that when I first started (the initial setup) this linking was already done.

Reading the docs about [OIDC linking accounts](https://docs.kitchenowl.org/latest/self-hosting/oidc/#linking-accounts) a little bit closer I understand that the 'flow' of the initial setup implies that you create an account and thus you are not linked and need to do this manually. 
This means that when I create accounts for my family (I will not allow `OPEN_REGISTRATION` for example) I have to tell them to:

1. Go to https://kitchenowl.domain.com
2. Press the "Sign in with OIDC" button and by doing so create an authenticated session with Authentik
3. Login KitchenOwl with username and password
4. Link their accounts

Or:

1. Go to https://kitchenowl.domain.com
2. Login KitchenOwl with username and password
3. Link their accounts
4. By either already having an Authentik session or creating one because of the linking action, the OIDC setup with/in KitchenOwl is done for them

Could you confirm if one or the other assumption is correct? Or that I made wrong assumptions on the flows and there is another way to go about this.

Perhaps the docs could explain this process of getting other people onboard with KitchenOwl. Explain the flow of activities the admin and users have to do to get someone properly on-boarded with KitchenOwl and OIDC.
Or I missed something and this is already done, could be.

Another thing I wondered about is that I do not want people on-boarding or registering themselves.
If I want to achieve this, and also disable the ability to login with username/password, I would set these option like so:
```
DISABLE_USERNAME_PASSWORD_LOGIN=true
DISABLE_ONBOARDING=true
OPEN_REGISTRATION=false
```
But in that case there will be no possibility for new users to login and link their account with OIDC. Am I correct in thinking this? If not, what would be the right approach to have new users in KitchenOwl with OIDC and no possibilities of registering yourself as a stranger and no username/password possibility active?

**Comment by B3RR10** [comment]
@reddwarf666 Adding my 2 cents here:

I deployed Kitchenowl yesterday for the first time and had no issues adding my wife as a user with her Authentik login. I have `DISABLE_USERNAME_PASSWORD_LOGIN=true` and `OPEN_REGISTRATION` is `false` by default.

She just logged in with OIDC and her account was automatically created.

She did it on her iPhone, and when she logged in to Authentik (in the in-built Safari), she had to manually close the browser/page after the fact, it was stuck loading. Then, she refreshed the app, and she was in.

@TomBursch Nice job with the app BTW 👍

**Comment by anhichang** [comment]
I could not login with iOs, so I did this and it works:

<img width="2108" height="198" alt="Image" src="https://github.com/user-attachments/assets/45858451-fa58-4d2f-9a4d-9edb9586ee4c" />

**Comment by shangri26199** [comment]
Sorry haven't seen the reply....
@reddwarf666 @J000K3R my Redirect URls look like this, almost like what @anhichang uploaded.

<img width="1039" height="94" alt="Image" src="https://github.com/user-attachments/assets/ccd0ca65-1cd0-4a52-abcf-da9c350b57bf" />

Since this is working, there may be some documentation missing but it's working and not a bug. Relabel?

**Comment by clbx** [comment]
Anyone coming across this issue, adding a signing key in the Authentik Provider fixed the issue the original poster had with the malformed JWKS token.
