### ISSUE TITLE
Bug: Backend container throwing error in Kubernetes

### ISSUE THREAD

**Issue by geoffbon** [TomBursch/kitchenowl#519]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

Docker hub tombursch/kitchenowl

### What is the client version

NA

### What platform are you using

Windows

### What's the problem 🤔

I'm trying to spin up a (home lab) Kubernetes container to try out KitchenOwl, but I'm getting the error shown in the logs below.

I'm using Rancher to manage Kubernetes, and I translated the docker compose from [here](https://github.com/TomBursch/kitchenowl/blob/main/docker-compose-single.yml) into the appropriate pieces on Rancher.  Normally this all works pretty well, especially when it's such a simple app (one port exposed, one storage entry) but for some reason it's not this time.  
I also tried 
* using `tombursch/kitchenowl:beta`.
* just setting up a backend with `tombursch/kitchenowl-backend:latest`.
* spinning up a postgres image as shown in [this compose file](https://github.com/TomBursch/kitchenowl/blob/main/docker-compose-postgres.yml) - the postgres container ran with no problems

The KitchenOwl container threw the same error in every case.

I'm hoping the below error is enough to indicate why something might be failing - any ideas?
Thanks!

### Share your logs

```Shell
Traceback (most recent call last):
  File "/opt/venv/bin/flask", line 8, in <module>
2024-09-28T19:50:00.884034749Z     sys.exit(main())
2024-09-28T19:50:00.884040289Z              ^^^^^^
2024-09-28T19:50:00.884046170Z   File "/opt/venv/lib/python3.12/site-packages/flask/cli.py", line 1105, in main
2024-09-28T19:50:00.884061399Z     cli.main()
2024-09-28T19:50:00.884068963Z   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-09-28T19:50:00.884157948Z     rv = self.invoke(ctx)
2024-09-28T19:50:00.884165673Z          ^^^^^^^^^^^^^^^^
2024-09-28T19:50:00.884172305Z   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
2024-09-28T19:50:00.884322655Z     cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-28T19:50:00.884338263Z   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
2024-09-28T19:50:00.884503311Z     cmd = self.get_command(ctx, cmd_name)
2024-09-28T19:50:00.884515022Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-28T19:50:00.884521894Z   File "/opt/venv/lib/python3.12/site-packages/flask/cli.py", line 611, in get_command
2024-09-28T19:50:00.884554476Z     app = info.load_app()
          ^^^^^^^^^^^^^^^
2024-09-28T19:50:00.884567580Z   File "/opt/venv/lib/python3.12/site-packages/flask/cli.py", line 339, in load_app
2024-09-28T19:50:00.884716106Z     app = locate_app(import_name, None, raise_if_not_found=False)
2024-09-28T19:50:00.884719682Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-28T19:50:00.884722047Z   File "/opt/venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
2024-09-28T19:50:00.884724441Z     __import__(module_name)
  File "/usr/src/kitchenowl/wsgi.py", line 4, in <module>
2024-09-28T19:50:00.884729411Z     from app import app, socketio, celery_app
2024-09-28T19:50:00.884731284Z   File "/usr/src/kitchenowl/app/__init__.py", line 1, in <module>
2024-09-28T19:50:00.884735071Z     from app.config import app, jwt, socketio, celery_app
2024-09-28T19:50:00.884737115Z   File "/usr/src/kitchenowl/app/config.py", line 54, in <module>
2024-09-28T19:50:00.884781106Z     DB_URL = URL.create(
2024-09-28T19:50:00.884784313Z              ^^^^^^^^^^^
2024-09-28T19:50:00.884787018Z   File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 211, in create
2024-09-28T19:50:00.884825449Z     cls._assert_port(port),
2024-09-28T19:50:00.884828705Z     ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 221, in _assert_port
2024-09-28T19:50:00.884876934Z     return int(port)
2024-09-28T19:50:00.884880220Z            ^^^^^^^^^
2024-09-28T19:50:00.884883076Z ValueError: invalid literal for int() with base 10: 'tcp://10.43.11.110:3306'
```

**Comment by TomBursch** [comment]
Looking at the logs it seems like you've set `DB_PORT` to `tcp://10.43.11.110:3306`? Can you make sure you've set the environment variables (https://docs.kitchenowl.org/latest/self-hosting/advanced/) correctly?

**Comment by SpeedyFireCyclone** [comment]
Hi @geoffbon, I happened to stumble upon this issue here. - The cause of this environment variable clobbering is a service named `db` in the same namespace.
Kubernetes injects additional environment variables in pods to help with discoverability, here are some other ones you will find: https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables
If you rename your service to something like `postgres` or `database`, things should start working perfectly smoothly.

**Comment by geoffbon** [comment]
> Hi @geoffbon, I happened to stumble upon this issue here. - The cause of this environment variable clobbering is a service named `db` in the same namespace. Kubernetes injects additional environment variables in pods to help with discoverability, here are some other ones you will find: https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables If you rename your service to something like `postgres` or `database`, things should start working perfectly smoothly.

Wow - that is outstanding, thankyou @SpeedyFireCyclone  - this was exactly it.  I'm amazed!  And great info on the injected environment variables in general.

That got the pod running, but it doesn't seem to accept connections on port 80, and I don't _think_ I'm doing anything different from other apps with similar setups, which all work.  Here's what I get in the logs, anyone have any suggestions?  Is it the root context I'm running it as?

````
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:344: SyntaxWarning: invalid escape sequence '\-'
2024-09-29T19:22:44.335132083Z   """Parses a quoted string.
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:355: SyntaxWarning: invalid escape sequence '\-'
2024-09-29T19:22:44.335143604Z   """Parses a token or a quoted-string.
2024-09-29T19:22:44.335427522Z /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:518: SyntaxWarning: invalid escape sequence '\-'
2024-09-29T19:22:44.335442350Z   """Parses a ()-style comment from a header value.
2024-09-29T19:22:44.345450961Z /opt/venv/lib/python3.12/site-packages/pyRdfa/termorcurie.py:61: SyntaxWarning: invalid escape sequence '\+'
2024-09-29T19:22:44.345468765Z   xml_application_media_type = re.compile("application/[a-zA-Z0-9]+\+xml")
2024-09-29T19:22:44.346937928Z /opt/venv/lib/python3.12/site-packages/pyRdfa/utils.py:131: SyntaxWarning: invalid escape sequence '\?'
2024-09-29T19:22:44.346956884Z   _unquotedChars = ':/\?=#~'
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
2024-09-29T19:22:46.002477596Z   return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
2024-09-29T19:22:46.002491240Z   return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
2024-09-29T19:22:46.006741939Z INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

Upgrading households: 0it [00:00, ?it/s]
Upgrading households: 0it [00:00, ?it/s]
[uWSGI] getting INI configuration from wsgi.ini
2024-09-29T19:22:48.577316405Z [uwsgi-static] added mapping for / => /var/www/web/kitchenowl
2024-09-29T19:22:48.577457748Z *** Starting uWSGI 2.0.26 (64bit) on [Sun Sep 29 19:22:48 2024] ***
2024-09-29T19:22:48.577475139Z compiled with version: 12.2.0 on 19 July 2024 14:07:15
2024-09-29T19:22:48.577481942Z os: Linux-5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024
2024-09-29T19:22:48.577487583Z nodename: kitchenowl-7cc5b8c646-tkdtt
2024-09-29T19:22:48.577492682Z machine: x86_64
2024-09-29T19:22:48.577498753Z clock source: unix
2024-09-29T19:22:48.577503823Z pcre jit disabled
2024-09-29T19:22:48.577509393Z detected number of CPU cores: 4
2024-09-29T19:22:48.577514373Z current working directory: /usr/src/kitchenowl
2024-09-29T19:22:48.577519302Z detected binary path: /opt/venv/bin/uwsgi
2024-09-29T19:22:48.577524361Z *** dumping internal routing table ***
2024-09-29T19:22:48.577529972Z [rule: 0] subject: path_info regexp: ^\/(?!api)[^\.]*$ action: static:/var/www/web/kitchenowl/index.html
2024-09-29T19:22:48.577535000Z *** end of the internal routing table ***
2024-09-29T19:22:48.577540160Z uWSGI running as root, you can use --uid/--gid/--chroot options
2024-09-29T19:22:48.577545190Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2024-09-29T19:22:48.577550189Z your memory page size is 4096 bytes
2024-09-29T19:22:48.577555118Z detected max file descriptor number: 1048576
2024-09-29T19:22:48.577560178Z !!! no /etc/mime.types file found !!!
2024-09-29T19:22:48.577565137Z - async cores set to 200 - fd table size: 1048576
2024-09-29T19:22:48.577581788Z lock engine: pthread robust mutexes
2024-09-29T19:22:48.577586988Z thunder lock: disabled (you can enable it with --thunder-lock)
2024-09-29T19:22:48.577750141Z uWSGI http bound on [::]:8080 fd 3
2024-09-29T19:22:48.577757414Z uwsgi socket 0 bound to TCP6 address [::]:5000 fd 6
2024-09-29T19:22:48.577763977Z uWSGI running as root, you can use --uid/--gi
d/--chroot options
2024-09-29T19:22:48.577769447Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2024-09-29T19:22:48.577774446Z Python version: 3.12.4 (main, Jul 10 2024, 19:07:59) [GCC 12.2.0]
Python main interpreter initialized at 0x7fa1b8d41fb8
2024-09-29T19:22:48.587443446Z uWSGI running as root, you can use --uid/--gid/--chroot options
2024-09-29T19:22:48.587450168Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2024-09-29T19:22:48.587456019Z python threads support enabled
2024-09-29T19:22:48.587461048Z your server socket listen backlog is limited to 100 connections
2024-09-29T19:22:48.587466138Z your mercy for graceful operations on workers is 60 seconds
mapped 4307328 bytes (4206 KB) for 200 cores
2024-09-29T19:22:48.588048381Z *** Operational MODE: async ***
2024-09-29T19:22:48.588207376Z uWSGI running as root, you can use --uid/--gid/--chroot options
2024-09-29T19:22:48.588211915Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2024-09-29T19:22:48.588214560Z spawned uWSGI master process (pid: 29)
spawned uWSGI worker 1 (pid: 30, cores: 200)
2024-09-29T19:22:48.588586703Z spawned uWSGI http 1 (pid: 31)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7fa1b8d41fb8 pid: 30 (default app)
2024-09-29T19:22:50.358524294Z *** running gevent loop engine [addr:0x55e532e9ab40] ***
````

**Comment by geoffbon** [comment]
Ok, scratch all that, I'm a dolt and had the ports reversed, ugh.  Looks great now!  Looking forward to trying it out.
